### PR TITLE
Containerize Morph-KGC in Docker & Poetry

### PR DESCRIPTION
**Pull request by LuciaCabanillasRodriguez**
This pull request introduces two significant updates:

1. Docker Containerization:

- Added a Dockerfile for Morph-KGC to facilitate containerization.

- Optional dependencies can be specified during the build process.

Example usage:

`docker build -t morph-kgc-app .`

`docker build -t morph-kgc-app --build-arg optional_dependencies="sqlite kafka" .`

The container is designed to mount a local directory for required files.

`docker run -v $(pwd)/files:/app/files morph-kgc-app files/config.ini`

1. Dependency Management with Poetry:

- Updated the project to use Poetry for dependency management.

Please review and merge at your convenience.

### CODE REVIEW

**Comment by LuciaCabanillasRodriguez** [comment]
Hi @arenas-guerrero-julian, just wanted to let you know that I've addressed and fixed the mentioned checks in the latest pull request!

**Comment by idomingu** [comment]
Hi! Is there any update on this? Many thanks!

**Comment by arenas-guerrero-julian** [comment]
Hi @idomingu @LuciaCabanillasRodriguez ,

Since I am not familiar with poetry I wonder what is the benefit of it.

**Comment by idomingu** [comment]
@arenas-guerrero-julian this PR was closed in favor of #225, which keeps hatch.

**Pull request closed without merging**
